-- ============================================================
-- LALSTUDY Knowledge Archive v1
-- Run this once in Supabase Dashboard -> SQL Editor.
--
-- Security model:
-- - RLS is enabled.
-- - No anon/authenticated policies are created.
-- - LALSTUDY accesses the archive only from Streamlit server-side
--   using SUPABASE_SECRET_KEY.
-- ============================================================

create extension if not exists pgcrypto;

create table if not exists public.knowledge_concepts (
    id uuid primary key default gen_random_uuid(),

    canonical_name text not null,
    normalized_name text not null unique,

    definition_ko text not null,
    definition_en text not null,

    mechanism_ko text not null default '',
    mechanism_en text not null default '',

    why_it_matters_ko text not null default '',
    why_it_matters_en text not null default '',

    prerequisites jsonb not null default '[]'::jsonb,

    difficulty text not null default 'intermediate'
        check (difficulty in ('basic', 'intermediate', 'advanced')),

    quality_status text not null default 'AI_GENERATED'
        check (quality_status in ('AI_GENERATED', 'REVIEWED', 'CURATED')),

    source_model text,
    hit_count bigint not null default 0,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.knowledge_aliases (
    id bigint generated by default as identity primary key,

    concept_id uuid not null
        references public.knowledge_concepts(id)
        on delete cascade,

    alias_display text not null,
    alias_normalized text not null unique,

    created_at timestamptz not null default now()
);

create index if not exists idx_knowledge_concepts_canonical_name
    on public.knowledge_concepts (canonical_name);

create index if not exists idx_knowledge_aliases_concept_id
    on public.knowledge_aliases (concept_id);

create or replace function public.set_lalstudy_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_knowledge_concepts_updated_at
    on public.knowledge_concepts;

create trigger trg_knowledge_concepts_updated_at
before update on public.knowledge_concepts
for each row
execute function public.set_lalstudy_updated_at();


create or replace function public.archive_increment_hit(
    p_concept_id uuid
)
returns void
language sql
security definer
set search_path = public
as $$
    update public.knowledge_concepts
    set hit_count = hit_count + 1
    where id = p_concept_id;
$$;


-- Public browser clients should not directly read or write the archive.
alter table public.knowledge_concepts enable row level security;
alter table public.knowledge_aliases enable row level security;

revoke all on table public.knowledge_concepts from anon, authenticated;
revoke all on table public.knowledge_aliases from anon, authenticated;

-- Backend secret keys operate with privileged server-side access.
grant all on table public.knowledge_concepts to service_role;
grant all on table public.knowledge_aliases to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on function public.archive_increment_hit(uuid) to service_role;
